{{- $additionalPorts := (include "status-service.customization.ports" $) }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "status-service.labels" . | nindent 4 }}
  name: status-service-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: "TCP"
    {{- if $additionalPorts }}
      {{- $additionalPorts | nindent 4 }}
    {{- end }}
  selector:
    {{- include "status-service.selectorLabels" . | nindent 4 }}
